language: java
sudo: false
dist: trusty

notifications:
    email: false

jdk:
  - oraclejdk9

install:
- chmod u+x *.sh
- ./prepare.sh
- ./clean.sh
- ./build.sh
- ./test.sh
- ./build.sh
- ./run_waro_main.sh

