language: java
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - oracle-java9-installer

jdk: oraclejdk9

notifications:
    email: false

before_install:
    - wget http://services.gradle.org/distributions/gradle-2.14.1-bin.zip
    - unzip gradle-2.14.1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-2.14.1
    - export PATH=$GRADLE_HOME/bin:$PATH

install:
- gradle prepare
- chmod u+x build.sh
- ./build.sh
- chmod u+x test.sh
- ./test.sh

